name: build-ios-app
on:
  push:
    branches:
      - 'main'
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: fastlane tests
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
